# Generated by Django 4.0 on 2022-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='ipPc',
            field=models.CharField(max_length=20, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='refPayu',
            field=models.CharField(max_length=1000, verbose_name='referenciaPagoPayu'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='dieta',
            field=models.CharField(max_length=100, verbose_name='dieta'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(max_length=20, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ipPc',
            field=models.CharField(max_length=20, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivelDeportivo',
            field=models.CharField(max_length=100, verbose_name='nivelDeportivo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='porque',
            field=models.CharField(max_length=100, verbose_name='porque'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipoCuerpo',
            field=models.CharField(max_length=100, verbose_name='tipoCuerpo'),
        ),
        migrations.AlterField(
            model_name='usuarioelsa',
            name='ipPc',
            field=models.CharField(max_length=20, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='usuarioelsa',
            name='nombreCompleto',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuarioelsa',
            name='password',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
    ]
