# Generated by Django 4.0 on 2022-08-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_membresia_ippc_alter_membresia_refpayu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='idPerfilUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarioelsa'),
        ),
    ]
